### ISSUE TITLE
Cannot read property 'from' of undefined

### ISSUE THREAD

**Issue by 10000multiplier** [lawrencecchen/threaded-comments#1]
Keep getting this error when I try to submit a comment.

Any thoughts on what could cause it?

Great work

![image](https://user-images.githubusercontent.com/57633368/116854364-91ebf880-abc5-11eb-9e53-d26933c9e51b.png)

**Comment by 10000multiplier** [comment]
this is the error `invalid input syntax for type bigint: "null"`

**Comment by lawrencecchen** [comment]
Make sure supabase is imported in the first case. I can't be sure why supabase doesn't exist if I can't see the source code. The id key just has to be a bigint type. In the example schema, it's an auto-incrementing bigserial type.

Your error message says that the database sees "null" when it's expecting a bigint. Again, I can't really help without seeing your schema and code.

**Comment by 10000multiplier** [comment]
here is the file in the question <script src="https://gist.github.com/10000multiplier/89882bcbb578bedf85bae0c82832205a.js"></script>

**Comment by 10000multiplier** [comment]
the db schema: 
![image](https://user-images.githubusercontent.com/57633368/116953061-46375e80-ac5a-11eb-8a69-ccd5a3f8630b.png)

**Comment by 10000multiplier** [comment]
It seems that the error is fired even before submitting a comment, and points to the use-comments.js file

![image](https://user-images.githubusercontent.com/57633368/117020327-56842380-acc4-11eb-8129-aeceb254ac52.png)

**Comment by lawrencecchen** [comment]
You've renamed a bunch of columns to use underscores rather than camel case. Did you make sure to update all the views as well? Do any comments appear when you manually add records to the table? Seeing your source code would help a lot w/ debugging.

**Comment by 10000multiplier** [comment]
Thanks.

Turns out the error was caused by importing supabase instead of { supabase } lol.

It works and it's amazing.

How long have you been coding if I may ask?

**Comment by lawrencecchen** [comment]
Great to hear! I don't have a technical coding job, but my father introduced me to coding in 1st grade. Didn't start doing much until recently, and I only started learning postgres/supabase this February. Gonna close this out for now, but you can find me on twitter for casual convos [here](https://twitter.com/lawrencecchen)
