### ISSUE TITLE
How to obtain comment count for a list of posts?

### ISSUE THREAD

**Issue by 10000multiplier** [lawrencecchen/threaded-comments#3]
fetching the comment count for a single post is a breeze using `const { count } = useComments()`

However, how would you go about fetching the comment count when you have a list of  multiple posts?

**Comment by lawrencecchen** [comment]
This subquery is what you want:
```sql
(
    select
        count (*) - 1 -- Remove self
    from
        comments_thread c
    where
        p.path <@ c.path
) as "childrenCount"
```
Add it to the `comments_thread_with_user_vote` view (or whichever one you're querying from the client) so that it looks like this:
```sql

create or replace view comments_thread_with_user_vote as
    select distinct on (id)
        p.id,
        p.slug,
        p."createdAt",
        p."updatedAt",
        p.title,
        p.content,
        p."isPublished",
        p."authorId",
        p."parentId",
        p.live,
        p."siteId",
        p."isPinned",
        p."isDeleted",
        p."isApproved",
        p."html",
        p."isSpam",
        p."author",
        p."votes",
        p."upvotes",
        p."downvotes",
        p."depth",
        p."path",
        p."pathVotesRecent",
        p."pathLeastRecent",
        p."pathMostRecent",
        coalesce(
            (
                select
                    v."value"
                from
                    votes v
                where
                    auth.uid() = v."userId" and v."postId" = p.id
            ),
            0
        ) as "userVoteValue",
        (
            select
                count (*) - 1 -- Remove self
            from
                comments_thread c
            where
                p.path <@ c.path
        ) as "childrenCount"
    from
        comments_thread p
```
I'm updating this project w/ an API (headless) version soon that will include this functionality out of the box. Stay tuned!

**Comment by 10000multiplier** [comment]
Awesome.

I seem to be doing something wrong though as `childrenCount` is returning the wrong number using the following query:

```
const { data: comments } = await supabase.from('comments_thread_with_user_vote').select('children_count')
```

**Comment by lawrencecchen** [comment]
I'll need a way to reproduce this to help you out. BTW what's your use case for selecting the `childrenCount` of every comment?

Here's a working example of child count [working](https://www.headlesscomments.com/posts/1/comments). (Try collapsing a comment)

**Comment by 10000multiplier** [comment]
Hmm I counted 50 comments in your example and childrenCount is saying 63.

My use case is displaying the number of comments per post.

Like so![image](https://user-images.githubusercontent.com/57633368/118164104-b54a4b00-b3f0-11eb-8781-025c33d65b8b.jpeg)

**Comment by 10000multiplier** [comment]
Specifically that thread is saying 26 children while I am only counting 13. ![image](https://user-images.githubusercontent.com/57633368/118164843-8e404900-b3f1-11eb-998c-bbef4240eacb.jpeg)

**Comment by lawrencecchen** [comment]
Hmm I see. Looking into it. Thanks for bringing this up!

**Comment by 10000multiplier** [comment]
Please let us know if you find a solution 🙂

**Comment by lawrencecchen** [comment]
Hey 10,000 multiplier. I haven't had much time to fix this. If you do figure out the right SQL query, I'd love to see it and add it to this repo! Otherwise, I'll probably get to this after school ends this semester :)

**Comment by 10000multiplier** [comment]
Ah bummer! Would the query look something like this maybe?

```javascript
select
   "parentId", count (*)
from
   posts
GROUP BY "parentId"
ORDER BY "parentId" Desc;

```

**Comment by lawrencecchen** [comment]
Just figured it out! Here's the query:
```sql
select
    count (distinct id) - 1 -- Remove self
from
    comments_thread c
where
    p.path <@ c.path
```

Just have to add `distinct` since the layers and layers of SQL views is adding some duplication. Please LMK if this doesn't fix everything. I might revisit the underlying tables/query structures since I've learned a lot more about the comments problem.

Also, I'm adding a headless api as an easy way to interface the database with any frontend, so stay tuned!

**Comment by lawrencecchen** [comment]
Entire view query for context:
```sql
create or replace view comments_thread_with_user_vote as
    select distinct on (id)
        p.id,
        p.slug,
        p."createdAt",
        p."updatedAt",
        p.title,
        p.content,
        p."isPublished",
        p."authorId",
        p."parentId",
        p.live,
        p."siteId",
        p."isPinned",
        p."isDeleted",
        p."isApproved",
        p."html",
        p."isSpam",
        p."author",
        p."votes",
        p."upvotes",
        p."downvotes",
        p."depth",
        p."path",
        p."pathVotesRecent",
        p."pathLeastRecent",
        p."pathMostRecent",
        coalesce(
            (
                select
                    v."value"
                from
                    votes v
                where
                    auth.uid() = v."userId" and v."postId" = p.id
            ),
            0
        ) as "userVoteValue",
        coalesce(
            (
                select
                    count (distinct id) - 1 -- Remove self
                from
                    comments_thread c
                where
                    p.path <@ c.path
            ),
            0
        ) as "childrenCount"
    from
        comments_thread p
```

**Comment by 10000multiplier** [comment]
Works like a charm!

I'm excited to see what else you come up with 😎
